### ISSUE TITLE
Home Page Revision from UI/UX

### ISSUE THREAD

**Issue by nathakusuma** [Yayasan-Lembaga-Miryam/website-ylm#3]
REVISI WEB YLM

![image](https://github.com/user-attachments/assets/96602dbc-748f-4c09-a5d8-07567569931d)
![image](https://github.com/user-attachments/assets/0facf0ca-492a-4e94-8f92-baf3485db7cc)
Tulisan buat Cerdas sm Kebersamaannya kepotong, lebih kebawahin lg aj

![image](https://github.com/user-attachments/assets/26c5d7a4-82a8-4b83-8804-214c95b62a78)
Udah oke sih cm scrollnya kecepetan, kurangi dikit aj biar ga ngebut ngebut

Udh sich, itu aj udh keren 🫡

**Comment by achmalll** [comment]
ok, I'll resolve this

**Comment by achmalll** [comment]
I've solved it at #4
